name: fingu-web-prototype-local
services:
  fingu-web-prototype-client-alpha:
    image: fingu-web-prototype-client-local
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    env_file:
      - .env